source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LiquidFloatingActionButton_Example' do
  pod "LiquidFloatingActionButton", :path => "../"
  pod 'SnapKit', '~> 4.0'
end

target 'LiquidFloatingActionButton_Tests' do
  pod "LiquidFloatingActionButton", :path => "../"

  
end
