source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!

target 'LiquidFloatingActionButton_Example' do
  pod "LiquidFloatingActionButton", :path => "../"
  pod 'SnapKit', '~> 5.0'
end

target 'LiquidFloatingActionButton_Tests' do
  pod "LiquidFloatingActionButton", :path => "../"

  
end
637078807 Blanca